/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_applevision_VisionOCR */

#ifndef _Included_com_applevision_VisionOCR
#define _Included_com_applevision_VisionOCR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_applevision_VisionOCR
 * Method:    recognizeText
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_applevision_VisionOCR_recognizeText
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
